-- Add course management and course-scoped assignments to an existing StudentSend database.
-- Run once in Supabase SQL Editor. Existing students and assignments are preserved.

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  course_code varchar(50),
  course_name varchar(255) not null unique,
  created_at timestamptz not null default now(),
  constraint courses_course_code_unique unique (course_code)
);

insert into public.courses(course_code, course_name) values
  ('TH101', 'ภาษาไทย'),
  ('MA101', 'คณิตศาสตร์'),
  ('SC101', 'วิทยาศาสตร์'),
  ('EN101', 'ภาษาอังกฤษ'),
  ('SO101', 'สังคมศึกษา')
on conflict (course_name) do nothing;

alter table public.courses add column if not exists class_name varchar(100);

alter table public.students add column if not exists course_id bigint references public.courses(id) on delete restrict;
alter table public.assignments add column if not exists course_id bigint references public.courses(id) on delete restrict;
create index if not exists students_course_id_idx on public.students(course_id);
create index if not exists assignments_course_id_idx on public.assignments(course_id);

create or replace function public.ensure_student_submissions()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'active' then
    insert into public.submissions(student_id, assignment_id, status)
    select new.id, a.id, 'pending'::public.submission_status
    from public.assignments a
    where a.status = 'active'
      and (a.course_id is null or a.course_id = new.course_id)
    on conflict (student_id, assignment_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists students_ensure_submissions on public.students;
create trigger students_ensure_submissions
after insert or update of status, course_id on public.students
for each row execute function public.ensure_student_submissions();

create or replace function public.ensure_assignment_submissions()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'active' then
    insert into public.submissions(student_id, assignment_id, status)
    select s.id, new.id, 'pending'::public.submission_status
    from public.students s
    where s.status = 'active'
      and (new.course_id is null or s.course_id = new.course_id)
    on conflict (student_id, assignment_id) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists assignments_ensure_submissions on public.assignments;
create trigger assignments_ensure_submissions
after insert or update of status, course_id on public.assignments
for each row execute function public.ensure_assignment_submissions();

alter table public.courses enable row level security;
revoke all on public.courses from anon;
grant select, insert, update, delete on public.courses to authenticated;
grant usage, select on sequence public.courses_id_seq to authenticated;
drop policy if exists "Active staff can manage courses" on public.courses;
create policy "Active staff can manage courses" on public.courses
for all to authenticated
using ((select public.is_active_staff()))
with check ((select public.is_active_staff()));
