-- StudentSend schema for Supabase (PostgreSQL).
-- Run in a new Supabase project's SQL Editor as postgres.
-- Teacher accounts are managed by Supabase Auth; add approved auth user IDs to app_users.

create type public.staff_role as enum ('admin', 'teacher');
create type public.student_status as enum ('active', 'inactive');
create type public.assignment_status as enum ('active', 'inactive');
create type public.submission_status as enum ('pending', 'submitted', 'checking', 'checked', 'returned', 'late');

create table public.app_users (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    role public.staff_role not null default 'teacher',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.courses (
    id bigint generated by default as identity primary key,
    course_code varchar(50),
    course_name varchar(255) not null,
    class_name varchar(100) not null default '',
    created_at timestamptz not null default now(),
    constraint courses_name_class_unique unique (course_name, class_name),
    constraint courses_code_class_unique unique (course_code, class_name)
);
insert into public.courses(course_code, course_name, class_name) values
    ('TH101', 'ภาษาไทย', ''), ('MA101', 'คณิตศาสตร์', ''), ('SC101', 'วิทยาศาสตร์', ''),
    ('EN101', 'ภาษาอังกฤษ', ''), ('SO101', 'สังคมศึกษา', '');

create table public.students (
    id bigint generated by default as identity primary key,
    student_code varchar(50) not null unique,
    student_name varchar(255) not null,
    class_name varchar(100),
    student_number integer check (student_number is null or student_number > 0),
    course_id bigint not null references public.courses(id) on delete restrict,
    qr_token varchar(100) not null unique default replace(gen_random_uuid()::text, '-', ''),
    status public.student_status not null default 'active',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index students_class_number_idx on public.students(class_name, student_number);
create index students_name_idx on public.students(student_name);
create index students_course_id_idx on public.students(course_id);

create table public.assignments (
    id bigint generated by default as identity primary key,
    assignment_code varchar(50) not null unique,
    assignment_name varchar(255) not null,
    subject varchar(255),
    course_id bigint not null references public.courses(id) on delete restrict,
    description text,
    due_date timestamptz,
    qr_token varchar(100) not null unique default replace(gen_random_uuid()::text, '-', ''),
    status public.assignment_status not null default 'active',
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create index assignments_due_date_idx on public.assignments(due_date);
create index assignments_name_idx on public.assignments(assignment_name);
create index assignments_course_id_idx on public.assignments(course_id);

create table public.submissions (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    assignment_id bigint not null references public.assignments(id) on delete cascade,
    status public.submission_status not null default 'pending',
    submitted_at timestamptz,
    checked_at timestamptz,
    score numeric(6,2),
    max_score numeric(6,2),
    remark text,
    received_by uuid references auth.users(id) on delete set null,
    checked_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint unique_student_assignment unique(student_id, assignment_id),
    constraint score_nonnegative check (score is null or score >= 0),
    constraint max_score_nonnegative check (max_score is null or max_score >= 0),
    constraint score_within_max check (score is null or max_score is null or score <= max_score)
);
create index submissions_status_idx on public.submissions(status);
create index submissions_assignment_status_idx on public.submissions(assignment_id, status);
create index submissions_student_status_idx on public.submissions(student_id, status);

-- Keep updated_at current for direct SQL and Supabase client updates.
create function public.set_updated_at()
returns trigger
as $$
begin
    new.updated_at := now();
    return new;
end;
$$ language plpgsql set search_path = '';

create trigger app_users_set_updated_at before update on public.app_users
for each row execute function public.set_updated_at();
create trigger students_set_updated_at before update on public.students
for each row execute function public.set_updated_at();
create trigger assignments_set_updated_at before update on public.assignments
for each row execute function public.set_updated_at();
create trigger submissions_set_updated_at before update on public.submissions
for each row execute function public.set_updated_at();

-- Create pending records as pairs are added. The unique constraint makes this safe to rerun.
create function public.ensure_student_submissions()
returns trigger
as $$
begin
    if new.status = 'active' then
        insert into public.submissions(student_id, assignment_id, status)
        select new.id, a.id, 'pending'::public.submission_status
        from public.assignments a
        where a.status = 'active' and (a.course_id is null or a.course_id = new.course_id)
        on conflict (student_id, assignment_id) do nothing;
    end if;
    return new;
end;
$$ language plpgsql set search_path = '';
create trigger students_ensure_submissions
after insert or update of status, course_id on public.students
for each row execute function public.ensure_student_submissions();

create function public.ensure_assignment_submissions()
returns trigger
as $$
begin
    if new.status = 'active' then
        insert into public.submissions(student_id, assignment_id, status)
        select s.id, new.id, 'pending'::public.submission_status
        from public.students s
        where s.status = 'active' and (new.course_id is null or s.course_id = new.course_id)
        on conflict (student_id, assignment_id) do nothing;
    end if;
    return new;
end;
$$ language plpgsql set search_path = '';
create trigger assignments_ensure_submissions
after insert or update of status, course_id on public.assignments
for each row execute function public.ensure_assignment_submissions();

-- Policies only grant database access to users explicitly registered as active staff.
-- Create/invite accounts in Supabase Auth, then register them in app_users using SQL Editor.
create function public.is_active_staff()
returns boolean
as $$
    select exists (
        select 1 from public.app_users u
        where u.user_id = (select auth.uid()) and u.active = true
    );
$$ language sql stable security definer set search_path = '';
revoke all on function public.is_active_staff() from public, anon;
grant execute on function public.is_active_staff() to authenticated;

alter table public.app_users enable row level security;
alter table public.courses enable row level security;
alter table public.students enable row level security;
alter table public.assignments enable row level security;
alter table public.submissions enable row level security;

revoke all on public.app_users, public.courses, public.students, public.assignments, public.submissions from anon;
grant select on public.app_users to authenticated;
grant select, insert, update, delete on public.courses, public.students, public.assignments, public.submissions to authenticated;
grant usage, select on sequence public.courses_id_seq, public.students_id_seq, public.assignments_id_seq, public.submissions_id_seq to authenticated;

create policy "Staff can read their own profile" on public.app_users
for select to authenticated using (user_id = (select auth.uid()));

create policy "Active staff can manage courses" on public.courses
for all to authenticated
using ((select public.is_active_staff()))
with check ((select public.is_active_staff()));

create policy "Active staff can manage students" on public.students
for all to authenticated
using ((select public.is_active_staff()))
with check ((select public.is_active_staff()));

create policy "Active staff can manage assignments" on public.assignments
for all to authenticated
using ((select public.is_active_staff()))
with check ((select public.is_active_staff()));

create policy "Active staff can manage submissions" on public.submissions
for all to authenticated
using ((select public.is_active_staff()))
with check ((select public.is_active_staff()));

-- After inviting a teacher/admin in Supabase Authentication, register their UUID:
-- insert into public.app_users(user_id, display_name, role)
-- values ('AUTH-USER-UUID', 'ชื่อครู', 'admin');
